apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.7.7   # <-- passende Chart-Version (prüfen mit `helm search repo bitnami/minio`)
    helm:
      valueFiles:
        - apps/minio/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
