apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/max-kandzia/demo-minikube-gitops.git'
    targetRevision: HEAD
    path: apps/minio
    helm:
      releaseName: minio
      chart: minio
      repoURL: https://charts.bitnami.com/bitnami
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
