apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.7.7
    helm:
      values: |
        service:
          type: NodePort
          nodePorts:
            minio: 32134
            console: 30784
        auth:
          rootUser: "minio"
          rootPassword: "miniopass"
        defaultBuckets: "dremio-demo"
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
