apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.dremio.com  # offizielle Helm Repo
    chart: dremio
    targetRevision: 23.1.0  # Beispiel Version, ggf. prüfen
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: standard
          size: 10Gi

        objectStore:
          type: s3
          s3:
            endpoint: "http://minio.minio.svc.cluster.local:9000"
            accessKey: "minio"
            secretKey: "miniopass"
            bucket: "dremio-demo"

        postgresql:
          host: "demo-postgres.demo-db.svc.cluster.local"
          port: 5432
          database: "dremio"
          user: "postgres"
          password: "postgres"  # Demo-Passwort, bitte anpassen
